services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring
  
  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    networks:
      - monitoring
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
        - ./prometheus/config:/etc/prometheus/
        - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - redis_exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
        - ./grafana/data:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge